updated dockerfile

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,16 +27,14 @@ jobs:
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build Docker Image
-        env: 
-          DEBUG: true
-        run: docker build -f Dockerfile -t lensassignment:latest . || echo "Docker build failed"
+        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/lensassignment:latest . || echo "Docker build failed"
 
 
       - name: Push Docker Image
-        env: 
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: docker push lensassignment:latest || echo "Docker push failed"
+       # env: 
+        #  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+         # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/lensassignment:latest || echo "Docker push failed"
 
     #  - name: Push to Google Container Registry
     #    env:
